# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{aura-insight}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["bretweinraub"]
  s.date = %q{2011-05-13}
  s.description = %q{ longer description of your gem}
  s.email = %q{bret@ckuru.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/aura-insight.rb",
    "lib/aura/etl.rb",
    "lib/aura/etl/sugar.rb",
    "lib/aura/etl_helper.rb",
    "lib/aura/metadata.rb",
    "lib/aura/metadata/db_connection.rb",
    "lib/aura/metadata/environment_namespace.rb",
    "lib/aura/metadata/environment_namespace_connection.rb",
    "test/helper.rb",
    "test/test_aura-insight.rb"
  ]
  s.homepage = %q{http://github.com/bretweinraub/aura-insight}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "test/helper.rb",
    "test/test_aura-insight.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<ckuru-tools>, [">= 0.0.9"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ckuru-tools>, [">= 0.0.9"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ckuru-tools>, [">= 0.0.9"])
  end
end

